[package]
name = "pe-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "pe_config"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
figment = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
